### ISSUE TITLE
congratulations

### ISSUE THREAD

**Issue by arademaker** [JulianEducation/CommandLineBasics#1]
Hi @Julian , nice tutorial! Thank you for making that available. I would like to understand more how you made it. Do you have directions? Eventually, I would like to translate to Portuguese too.

**Comment by Julian** [comment]
Hi there! Thanks Alexandre, glad to hear it!

The basics I got from the [Google Cloud Shell Tutorial](https://cloud.google.com/shell/docs/cloud-shell-tutorials/tutorials) -- does that help at all?

A translation would be awesome! When I've given this seminar/lecture I'm sure I've had folks who'd benefit from localized versions (probably including Portuguese) so that'd be great to have!

**Comment by arademaker** [comment]
Nice! So I will take a look in the tutorial above. If you already have a clear idea how to add translations, let me know. I would be happy to collaborate making PR.

**Comment by Julian** [comment]
I'm not sure there'll be anything fancy for translations, Google Cloud Shell Tutorials are pretty bare bones, so it may simply be a matter of having multiple copies of the file (I'm not sure how easy it is to get something "fancier" which really supports keeping translations in sync, like gettext, working with Markdown either, perhaps that's a thing... would have to investigate).
